/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 02 17:12:15 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     3


#endif //_CUST_AUXADC_TOOL_H


