/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 02 17:12:15 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


